const app=document.querySelector('#app');let page='home';let dark=localStorage.dark==='1';let fav=new Set(JSON.parse(localStorage.fav||'[]'));document.body.classList.toggle('dark',dark);
const demo={fixtures:[
{id:1,league:'Premier League',home:'Liverpool',away:'Manchester City',time:'20:00',status:'NS',score:'-'},
{id:2,league:'La Liga',home:'Barcelona',away:'Real Madrid',time:'22:00',status:'NS',score:'-'},
{id:3,league:'Serie A',home:'Inter',away:'AC Milan',time:'21:45',status:'NS',score:'-'},
{id:4,league:'Saudi Pro League',home:'Al Hilal',away:'Al Nassr',time:'20:30',status:'NS',score:'-'}]};
async function api(path){try{let r=await fetch('/api/'+path);if(!r.ok)throw 0;return await r.json()}catch(e){return null}}
function card(m){let k=m.id;return `<div class="card"><div class="row"><span class="badge">${m.league||'Football'}</span><button onclick="toggle(${k})">${fav.has(String(k))?'★':'☆'}</button></div><div class="match"><div class="team">${m.home}</div><div><div class="${m.status==='LIVE'?'live':''}">${m.status==='LIVE'?'مباشر':m.status||''}</div><div class="score">${m.score||'-'}</div><small>${m.time||''}</small></div><div class="team">${m.away}</div></div></div>`}
function toggle(k){k=String(k);fav.has(k)?fav.delete(k):fav.add(k);localStorage.fav=JSON.stringify([...fav]);render()}
async function render(){document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));let live=await api('live');let today=await api('today');let f=today?.fixtures||demo.fixtures;if(page==='home')app.innerHTML=`<div class="wrap"><div class="hero"><h1>⚽ كورة بلس</h1><div>كل مباريات كرة القدم في مكان واحد</div></div><h2>مباريات اليوم</h2>${f.map(card).join('')}</div>`;if(page==='live'){let x=live?.fixtures||[];app.innerHTML=`<div class="wrap"><div class="hero"><h1>🔴 مباشر</h1><div>النتائج لحظة بلحظة</div></div>${x.length?x.map(card).join(''):'<div class="empty">لا توجد بيانات مباشرة الآن.</div>'}</div>`}if(page==='leagues')app.innerHTML=`<div class="wrap"><div class="hero"><h1>🏆 البطولات</h1></div><div class="grid">${['Premier League','La Liga','Serie A','Bundesliga','UEFA Champions League','Saudi Pro League','Egyptian Premier League','Sudanese Premier League'].map(x=>`<div class="card"><b>${x}</b></div>`).join('')}</div></div>`;if(page==='fav'){let x=f.filter(m=>fav.has(String(m.id)));app.innerHTML=`<div class="wrap"><div class="hero"><h1>⭐ المفضلة</h1></div>${x.length?x.map(card).join(''):'<div class="empty">لا توجد مباريات مفضلة.</div>'}</div>`}}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{page=b.dataset.page;render()});document.querySelector('#theme').onclick=()=>{dark=!dark;localStorage.dark=dark?'1':'0';document.body.classList.toggle('dark',dark)};document.querySelector('#refresh').onclick=render;render();setInterval(()=>{if(page==='live')render()},30000);